# Site settings
title: ειδωςκοπ - Le projet
tagline : eidoskop Lunette pour le metaverse
email: etxetxe6433@gmail.com
url:
description: "Explorez des mondes en réalité multiple à la lunette "

mots-cles: "XR, AR, VR, MR, virtual production"

locale:                 fr_FR

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: eidoskop

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/etxetxe

# Build settings

timezone:               Etc/UTC

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - VR_test.gif
  - screenshot.png
  - 20210319_151610.jpg
  - GitVR.uproject

permalink: /:path/
output: true

# ------------
repo_url:             https://github.com/etxetxe/VR_Bifurcation
repo_branch:          master
